---
abstract: unknown
author:
  - unknown
build_requires:
  ExtUtils::MakeMaker: 0
configure_requires:
  ExtUtils::CBuilder: 0.27
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.8, CPAN::Meta::Converter version 2.132830'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Devel-GlobalDestruction
no_index:
  directory:
    - t
    - inc
requires:
  Sub::Exporter::Progressive: 0.001006
resources:
  bugtracker: http://rt.cpan.org/Public/Dist/Display.html?Name=Devel-GlobalDestruction
  homepage: http://search.cpan.org/dist/Devel-GlobalDestruction
  repository: git://git.shadowcat.co.uk/p5sagit/Devel-GlobalDestruction.git
version: 0.12_01
